### ISSUE TITLE
Question: supporting dd/img type disk image format

### ISSUE THREAD

**Issue by LevelBest-2004** [AppleCommander/AppleCommander#102]
This tool is so powerful, I was hoping it would allow me to write images to a real disk.  Many who work with disk images also have physical machines, but I don't see an option to write a real disk.  Would it be possible to support conversion to an img/dd output format  that could then be written to a real disk using a common raw write style of disk image writer found easily on windows and linux?  Or would one of the existing formats be a sequential sector format that may already work with one of these image->disk tools?

**Comment by lebraseric** [comment]
I don't know if this feature exists in AppleCommander, however you also have the option of using (FUSE ProDOS FUSE filesystem), which is included with GoldenGate (but requires that you actually buy GoldenGate).
<https://goldengate.gitlab.io/>

**Comment by a2geek** [comment]
Sorry, this is not a feature of AppleCommander. There are a number of tools that are useful:
* Golden Gate (listed above, https://goldengate.gitlab.io/, commercial)
* ADT Pro (https://www.adtpro.com/)
* Apple ][ Disk Server (https://asciiexpress.net/diskserver/)
I'm certain there are a lot more.

For myself, what I've done is hookup a serial connection to a Linux server. I then hop into ProTERM on the Apple2, log into the Linux machine, and start a Zmodem transfer.
