### ISSUE TITLE
Text file in File View shows as blank. Exports nothing.

### ISSUE THREAD

**Issue by kevin-chau** [AppleCommander/AppleCommander#106]
I have a text file called HELLOWORLD.TXT created with Apple Writer II. When I open it in the File View, it shows up as blank in the "Text" view:
<img width="561" alt="image" src="https://github.com/AppleCommander/AppleCommander/assets/6045301/945d05bf-c33a-432a-bd38-4d4d07f71b4f">

The "Hex Dump" view shows the correct characters ("Hello"):
<img width="566" alt="image" src="https://github.com/AppleCommander/AppleCommander/assets/6045301/9462bd6e-f4b5-41f6-a4bb-2f005841327d">

Exporting as "ASCII text file" creates a completely empty file (0 bytes). Exporting as "Raw disk data" produces the correct text file, which is viewable in any text editor.

**Comment by ryandesign** [comment]
AppleCommander is evidently expecting the text file to end with a carriage return (`0D`). I crafted a multiline text file and omitted the carriage return from the end of the last line and AppleCommander displayed every line except the last one. I'm not familiar with Apple Writer II but if it creates text files that don't end with a carriage return then it would be reasonable for AppleCommander to support displaying them fully.

The Apple II normally stores characters with the high bit set, so whereas HELLO in ASCII is `48 45 4C 4C 4F` as in your example, a text file containing HELLO saved from Applesoft BASIC would contain `C8 C5 CC CC CF`. That goes for the carriage return as well (`8D`). AppleCommander appears to support displaying text files whether or not the high bit is set on each character.

**Comment by a2geek** [comment]
Wow, I wonder how long this has been an issue. (And, did it change over time due to Java upgrades??)

Thanks for the comments, @ryandesign, that's exactly what it was. The Java PrintWriter only flushes when a newline is encountered. I just added a forced flush to ensure all the output is captured.
