### ISSUE TITLE
acx import not working with as flag

### ISSUE THREAD

**Issue by markjfisher** [AppleCommander/AppleCommander#108]
Am I correct in assuming the following should be the same functionally when trying to add the file "hello" as "test" in a disk named "cc65.po", formatted in prodos format?

```shell
$ ac -as cc65.po test < hello
$ acx import -d cc65.po --stdin --as -n test < hello
$ acx import -d cc65.po hello --as -n test
```

Only the first command allows the file to be run correctly from DOS (it's a simple Hello World app).

In the other cases, using `acx import` when I try to BRUN the program I get:

<img width="882" alt="image" src="https://github.com/AppleCommander/AppleCommander/assets/1616940/b8b24967-0a41-4c36-9c8e-d6a353a19db7">

**Comment by a2geek** [comment]
Definitely a bug. I think it's maybe not what is expected, however. Try setting the address in those commands:
```
$ acx import -d cc65.po --stdin --as -n test -a 0x803 < hello
$ acx import -d cc65.po hello --as -n test -a 0x803
```
(or whatever your start address is -- I think it's $803 by default).

**Comment by markjfisher** [comment]
Thanks for this, sorry I didn't have time to test your suggestions out. Glad you got it sorted.
