### ISSUE TITLE
Some text is cut off in Create, Compare, and Compile wizards

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#113]
With AppleCommander 1.8.0 on macOS Monterey 12.6.8, some text is cut off at the top of the Disk Image Wizard and the Compare Disks Wizard: 

![Disk Image Wizard](https://github.com/AppleCommander/AppleCommander/assets/429209/6b2ae550-19c8-43f6-a540-a2d4704fd843)

![Compare Disks Wizard](https://github.com/AppleCommander/AppleCommander/assets/429209/2a043029-f172-4f02-9d8a-5278275b0c80)

This was previously mentioned in https://github.com/AppleCommander/AppleCommander/issues/67#issuecomment-1063641306.

**Comment by ryandesign** [comment]
Also affects the Compile Wizard:

![Compile Wizard](https://github.com/AppleCommander/AppleCommander/assets/429209/daf1945f-3555-4d80-b73a-690ac15a3d1b)

**Comment by a2geek** [comment]
I just committed a start. I don't remember enough about SWT if it was word-wrapping text or not before. I couldn't get it to wrap, but I also noticed that there were newline `\n` characters embedded, so I adjusted them. I'm currently on a Linux box, so I'll have to remember to try this on my Mac as well. And maybe Windows if that laptop is still working. (Crazy!)

**Comment by ryandesign** [comment]
Thank you, it doesn't look much better with those changes on macOS though.

![diwiz](https://github.com/AppleCommander/AppleCommander/assets/429209/8a5ffc12-c54b-41cf-a56e-0cd104141974)

![ciwiz](https://github.com/AppleCommander/AppleCommander/assets/429209/93a71886-bc28-40cb-9035-bee6a25fa279)

Similar to #121, I think not embedding hard newlines in sentences should result in the best rendering across different devices with different font metrics and sizes, it's just a problem of getting the text to start off at the correct top left coordinate. It's surprising that this isn't straightforward to do!

**Comment by ryandesign** [comment]
Is this the same problem you mentioned seeing in https://github.com/AppleCommander/AppleCommander/issues/67#issuecomment-1063641306?

I'm beginning to doubt my sanity because what I'm noticing now is that if I open one of these wizards, the middle pane is positioned wrong (too far up, behind the header image, as shown in the screenshots), but if I leave it open, switch to another app, and come back a minute or two later, it has fixed itself.

I've checked two other Macs (one running macOS Sierra 10.12.6, the other running macOS Catalina 10.15.7) and they draw the wizards correctly from the beginning. It's only my main machine running macOS Monterey 12.6.8 where it's drawn wrong initially. I will admit that this machine is having some other problems—various tasks being far slower than they have any right to be—so it could be something uniquely wrong with my computer, possibly related to the enormous number of windows that I seem to keep open at all times. Unless you confirm this is what you saw on yours as well.

I'm wondering now if it's just a matter of something not getting initialized in time for the initial layout. For example, the header image must of course be loaded in, and you're accessing its properties like width and height:

https://github.com/AppleCommander/AppleCommander/blob/0bccdde28a5fe9084056ff79559604a29d61502d/lib/ac-swt-common/src/main/java/com/webcodepro/applecommander/ui/swt/wizard/Wizard.java#L82-L86

I know that JavaScript is not Java, but for example in JavaScript if you load an image or other external resource, it happens asynchronously and you need to wait for the notification that the resource has been loaded before you can use it. Might something similar apply here?

**Comment by a2geek** [comment]
If you have a moment, if you could review this build, that would be great: https://github.com/AppleCommander/AppleCommander/actions/runs/6715772770

I *think* I'm seeing that the content window of the wizard is (somehow) ignoring the title header. I set each background to a different color while I was debugging and I saw the primary content window was still visible once a wizard window was drawn. Shifted up by about the dialog title's height (and apparently under that image). This is really a hack in that the dialog title gets turned off ("sheet" mode meant nothing to me, but that's what I think is going on).

As far as the images, they are loaded and cached when the application launches. I did print out the dimensions of the image as well, and got legit numbers. So, unfortunately not that simple!

**Comment by a2geek** [comment]
I should mention that my Mac did see the issue (which I've been ignoring since I am most definitely not a user interface person!), and this did fix it for my Mac. I know you indicated you had different experiences on your different Macs. So hopefully this works across all of them! It looks good on my Linux desktop as well (which makes sense due to the patch I put in being only for the Mac). I'll try to see if my Windows machine still works... then I can verify there as well. After it gets up-to-date after the last time I turned it on. :-)

**Comment by ryandesign** [comment]
It looks great now, thanks.

![diwizardsheet](https://github.com/AppleCommander/AppleCommander/assets/429209/d63009ac-0016-4b90-ad60-cb59e69e1345)

Not sure why enabling sheet mode fixes it, but I'm glad it does, because that actually resolves another UI issue I hadn't reported yet, which is that the wizard's window looked like it was independent of the main window and could be dragged and moved separately, but also dragging the main window while a wizard was up caused both windows to move; that's not usual macOS behavior. Turning it into a sheet, thereby removing its titlebar and its ability to be moved independently and anchoring it to the window, clarifies that it descends from the main window and resolves the UI inconsistency: sheets are indeed supposed to move with their parent window.
