### ISSUE TITLE
Naming inconsistency: Compare Disks Wizard vs Compare Image Wizard

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#114]
With AppleCommander 1.8.0, when I click the Compare… toolbar button, a window opens. The titlebar of the window reads "Compare Disks Wizard" while the header image inside it reads "Compare Image Wizard":

![Compare Disks Wizard](https://github.com/AppleCommander/AppleCommander/assets/429209/2a043029-f172-4f02-9d8a-5278275b0c80)

The two texts should be the same.

(The problem with the cut-off text just below the header image is #113.)

**Comment by ryandesign** [comment]
Thanks, e0e16e5325277dcec822384f7ab37e2f2089d8f2 fixes it. Do you want to leave these issues open until you release a new version or should I close them once they're confirmed fixed?

**Comment by a2geek** [comment]
I'm never certain. Closing out as I prepare for the release. Thanks!
