### ISSUE TITLE
Syntax-highlighted BASIC code unreadable in dark mode

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#115]
Using AppleCommander 1.8.0 on macOS with dark mode enabled (available in macOS 10.14 or later), the syntax-highlighted code I see when I open a disk image, select a BASIC file, and click the View toolbar button is unreadable because line numbers are printed in black (on a dark gray background) and commands are shown in dark blue:

![View](https://github.com/AppleCommander/AppleCommander/assets/429209/d5271976-257d-453a-9d08-510dc6992808)

**Comment by a2geek** [comment]
This was annoying me too! Just not enough to hunt down.

**Comment by ryandesign** [comment]
After 9a300d1241c54f53132b0ab7ab21c0e065dfab2a it looks good, thanks!

![syntax-highlighting-dark](https://github.com/AppleCommander/AppleCommander/assets/429209/8409bf40-0e20-4ec4-af64-b182172e0a0d)

![syntax-highlighting-light](https://github.com/AppleCommander/AppleCommander/assets/429209/4eaf0f31-77c1-40cc-a383-d5d0ad75851c)
