### ISSUE TITLE
Export Wizard destination field unreadable in dark mode

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#116]
In AppleCommander 1.8.0 on macOS set to dark mode (available in macOS 10.14 and later), if I open a disk image, select a file, click the Export… toolbar button, then click Next >, it asks me to select a destination:

![Export Wizard](https://github.com/AppleCommander/AppleCommander/assets/429209/8c881651-4d2d-4e7a-b958-2ef06d8c7c89)

But even after clicking the Browse… button and selecting a destination, the destination field remains empty. Turns out the destination has been selected properly but is being drawn in white text (which is correct for dark mode) on a white background (which is incorrect for dark mode). The destination becomes visible if I select the contents of the field:

![Export Wizard selected](https://github.com/AppleCommander/AppleCommander/assets/429209/3daa7e83-0d21-440f-8a2a-01e6a42d7634)

**Comment by a2geek** [comment]
The background was intentionally being set to white. I removed that to allow the tooling to pick appropriate colors.

**Comment by ryandesign** [comment]
Thank you, b3a5f3e9dfe8ee794c1848e1244b75896f292491 fixes it for the Export Wizard and e3a0844fbd130239d4755bca7c90adfede383173 fixes it for the Compile Wizard.
