### ISSUE TITLE
No confirmation for destructive actions

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#117]
With AppleCommander 1.8.0 on macOS Monterey 12.6.8, my changes to disk images are silently discarded unless I explicitly click the Save toolbar button.

To reproduce:

1. Open a disk image
2. Modify it in some way (for example: select a file and delete it, which asks "Are you sure you want to delete this file?" and I click Yes)
3. Notice that the modification has taken place (for example: the file is no longer in the listing)
4. Close the window

No alert appears asking me whether I want to save the changes to the disk image before closing it. I might assume therefore that changes get saved automatically. However, if I reopen the disk image, the file I deleted is still there. My changes were lost.

**Comment by a2geek** [comment]
Found a cute little bug as well. The disks always assumed they had changed. The "save" button should toggle if a change was made, but that change tracking was faulty!

**Comment by ryandesign** [comment]
Thanks. Now, I do get get asked for confirmation if I try to close the disk window:

> The disk has been modified. Are you certain you want to quit? [No] [Yes]

![AppleCommander](https://github.com/AppleCommander/AppleCommander/assets/429209/3879bc29-33a9-4b4f-b3b5-268c06e04393)

However, a couple things.

First, I wasn't quitting; I was closing the disk window.

Second, such dialog boxes typically give *three* buttons: one to save the changes and close the document, one to discard the changes and close the document, and one to leave the document open. You've given us the last two options but not the first one, and you've labeled the buttons in a way that is counterintuitive to me as a Mac user by asking the inverse of the question I'm used to being asked and by making the destructive action the default button.

On Macintosh System 6 and earlier, such dialog boxes typically asked a question like "Do you want to save changes?" and the buttons were customarily labeled "Yes", "No", and "Cancel":

![TeachText 6](https://github.com/AppleCommander/AppleCommander/assets/429209/7414a3a0-0d7b-4e12-8b1c-6d243da2cb1c)

On System 7 and later, the custom changed so that the dialog text included the name of the application and the name of the document (which can be helpful if you have many documents or applications open) and the buttons were then labeled "Save", "Don't Save", and "Cancel" to make them clearer, and the destructive button was moved to be visually separate from the non-destructive buttons:

![TeachText 7](https://github.com/AppleCommander/AppleCommander/assets/429209/26a3b0b9-a8c5-4a8d-8350-0a41daf4cfac)

This custom persists on macOS today in apps that don't implement autosave:

![BBEdit](https://github.com/AppleCommander/AppleCommander/assets/429209/92804954-a3f0-485e-b16b-24b380fc307a)

I don't know if there's a particular custom in Java for this kind of thing but you might look at what other Windows and Linux GUI apps (not necessarily written in Java) do.

Third, while I get this confirmation if I close the disk window, I do not get any message if I close the main application window; it quits and discards my changes.

Fourth, if I choose Quit from the AppleCommander menu, it also quits without confirmation.

**Comment by a2geek** [comment]
Moved continuation to #132.
