### ISSUE TITLE
Nonfunctional About menu item on macOS

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#118]
With AppleCommander 1.8.0 on macOS, clicking the About toolbar button works fine and displays the about message. But on macOS, all applications have a menubar which always contains at least an Apple menu and an application menu, and the application menu always has standard menu items starting with About and ending with Quit:

![menu](https://github.com/AppleCommander/AppleCommander/assets/429209/871cb742-e67a-4c12-a333-97a10a724e31)

If I select the About item, nothing happens. It should do the same thing as clicking the About toolbar button.

**Comment by a2geek** [comment]
I think I finally found out how to do this. Way harder than it should be!!

**Comment by ryandesign** [comment]
Thanks! That fixed it.
