### ISSUE TITLE
Import Wizard doesn't disable Edit and Remove buttons after editing item; crashes when clicked

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#125]
Similar to #120, try these steps:

1. Create a new DOS disk image or open an existing one.
2. Click Import… in the toolbar.
3. In the Import Wizard, note that the Remove and Edit… buttons are disabled because there are no items yet.
4. Click Choose… and select any file. The Remove and Edit… buttons are still disabled because no items are selected.
5. Select the file you added. The Remove and Edit… buttons enable.
6. Click Edit…, then click OK.
7. The list item has been deselected but the Remove and Edit… buttons are still enabled.
8. Clicking Remove causes the Remove and Edit… buttons to be disabled, but instead clicking Edit… causes AppleCommander to crash.

**Comment by ryandesign** [comment]
Or maybe the bug is that returning from the Edit… box by pressing the OK button deselects the item. Maybe it shouldn't do that. It doesn't do that when returning from the Edit… box via the Cancel button.

**Comment by a2geek** [comment]
I have a hack in place that should fix -- regardless of OK or Cancel being pressed, I deselect items in the list and disable buttons. Oddly, I can get information on when an item is selected in the list but not when one gets deselected, so had to choose what should happen!

**Comment by ryandesign** [comment]
I suppose that does prevent the crash, so that's good. But it seems like leaving the item selected, regardless how the dialog was exited, is the preferable UI. Are you saying SWT makes it impossible to do that?
