### ISSUE TITLE
[gradle] .gitignore cleanup

### ISSUE THREAD

**Issue by iKarith** [AppleCommander/AppleCommander#15]
The gradle branche's .gitignore file currently contains:

```
bin
AppleCommander.preferences
*.dsk
*.po
*.hdv
*.do
*.2mg
*.2img
.uml
TODO.local
*.jpage
work
TestImage.*
**/Thumbs.db
*.o
*.lst
.classpath
.project
.settings
.gradle
build/
target/
.DS_Store
```

Of these, because I do not use Eclipse, I see only need for:

```
*.dsk
*.po
*.hdv
*.do
*.2mg
*.2img
TODO.local
.gradle
build/
```

What else is needed? .settings, .classpath (maybe?) and .project?  Anything else?

[Edit: .DS_Store was already on the list, I thought I'd added that locally.)

**Comment by a2geek** [comment]
Maybe break into sections so we know why it's in there?  I think the Eclipse stuff we keep (it'll annoy me, for one ;-) ).  If we can't classify it, we can cut it then!

**Comment by iKarith** [comment]
The problem is I don't use eclipse and have never been much of an IDE user since about the Turbo C++/Pascal days really, so I don't know what is what, nor what is outdated.  I believe these are:

.settings
.classpath
.project

There's also .uml, but I don't know if that is Eclipse or not?  If it's a JavaDoc thing, we may not need it.  If it's something Eclipse creates, that's another story.

**Comment by iKarith** [comment]
This looks resolved.
