### ISSUE TITLE
Disk Image from Asimov leads to infinite loop with memory allocation

### ISSUE THREAD

**Issue by Lisias** [AppleCommander/AppleCommander#18]
Greetings.

I'm currently running a bunch of tests on Asimov's disk images, and ran into this issue. Some disk images (and there's more than one) leads into what appears to be an infinite loop with memory being crazily allocated until the process dies by lack of heap space.

The offending file is linked on this issue and explicitly detailed below.

### Initial analysis

The profiling leads me to think that the problem is being triggered by ` fd.getFiles()` call. 

Profiling the testbed hints that, perhaps, this image has a recursive directory listing (or some data/garbage/code that tricked Apple Commander into thinking it's a directory, and by bad luck the thing is recursive): the instanced objects counting for `com.webcodepro.applecommander.storage.os.dos33.DosFileEntry` blows up the roof

#### Evidences

* IMAGE_1_Graph.png
    + ![image_2_graph](https://user-images.githubusercontent.com/64334/33461560-1b5519b0-d61a-11e7-8a99-444260df8363.png)
    + Heap grows up and never shrinks
    + CPU activity has peaks of processing, suggesting the GC is working frequently (just a guess, I didn't profiled it)
* IMAGE_1_Graph.png
    + ![image_1_graph](https://user-images.githubusercontent.com/64334/33461494-dc0bdfaa-d619-11e7-9ff7-4fccd74e8e8c.png)
    + A second run confirmed the behaviour.
* IMAGE_2_MemProfiling.png
    + ![image_2_memprofiling](https://user-images.githubusercontent.com/64334/33461600-50ca07f4-d61a-11e7-8d0c-ec78eedc7c1a.png)
    + Memory profiling suggests the code that instances `com.webcodepro.applecommander.storage.os.dos33.DosFileEntry` is directly involved in the problem.

### HOW TO REPRODUCE
1. Download the offending file
1. Set up an environment variable called `DATA` pointing into the directory where you downloaded the files
1. run the test code quoted below.

#### Offending file

Here: ftp://ftp.apple.asimov.net//pub/apple_II/images/misc/3d0g_knight_collection/013b - Congo Bongo.dsk

#### Testbed Source code

```java
package examples.a2cmdr;

import java.io.File;
import java.io.IOException;
import java.util.List;

import com.webcodepro.applecommander.storage.Disk;
import com.webcodepro.applecommander.storage.FileEntry;
import com.webcodepro.applecommander.storage.FormattedDisk;

public class test {

	public static void main(String[] args) {
		final File data = new File(System.getenv().get("DATA"));

		for (File f : data.listFiles()) {
			System.out.println(f.getName());
			show_disk(f.getAbsoluteFile());
			System.out.println();
		}

	}

	private static void show_disk(final File diskfile) {
		try {
			final Disk d = new Disk(diskfile.getAbsolutePath());
			final FormattedDisk[] fds = d.getFormattedDisks();
			for (FormattedDisk fd : fds) {
				String disk_format = null;
				for (FormattedDisk.DiskInformation i : fd.getDiskInformation()) {
					if ("Disk Format".equals(i.getLabel())) disk_format = i.getLabel();
					System.out.println(String.format("\t%s : %s", i.getLabel(), i.getValue()));
					show_files(disk_format, fd.getFiles(), 2);
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	private static void show_files(final String disk_format, final List<FileEntry> files, final int i) {
		// TODO Auto-generated method stub

	}

}
```

#### Expected (offending) result

```java
013b - Congo Bongo.dsk
	File Name : /Users/lisias/code/net.lisias/net.lisias.retro/JAVA/data/a2/disks.bad/013b - Congo Bongo.dsk
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at com.webcodepro.applecommander.storage.os.dos33.DosFormatDisk.getFiles(DosFormatDisk.java:147)
	at examples.a2cmdr.test.show_disk(test.java:33)
	at examples.a2cmdr.test.main(test.java:18)
```

**Comment by Lisias** [comment]
This is blocking a pet project of mine. I intend to pursue this matter.

How do you guys wants me to handle this? As a recursive loop is detected, what Exception (and what text) you want me to throw?

**Comment by a2geek** [comment]
That's awesome!  Looking forward to this pull request, I like this initial approach.  I've been busy and just wanted to let you know I appreciate the finding and the effort!

**Comment by Lisias** [comment]
On the "back end", things worked very well. I can parse *all* the asimov's disk images with success. The DiskException is being thrown when appropriated.

But the UI is kaput. I really messed up something (perhaps on my runtime environment, I didn't managed to find time to check what's happening yet) - no disk image's content is being rendered on the Panel. The thing doesn't blows up, but doesn't works correctly neither.

I had forked this repo and created a branch for this issue. Is someone is willing to give me a hand on the UI, you're welcome. :-)

Branch: https://github.com/Lisias/AppleCommander/tree/issues/18

**Comment by Lisias** [comment]
Holy Crud!!! I was trying to make a screenshot with the problem, and the thing suddenly works! :-)

It's my running environment for sure. Something just fixed itself on the last eclipse update. =D

I will spend some hours trying to break the thing to see what happens in the next few days. If everything goes fine, I'll do a push request. :-)

**Comment by Lisias** [comment]
Pull Request at

https://github.com/AppleCommander/AppleCommander/pull/19

**Comment by Lisias** [comment]
I updated the pull request, with the proposal fixes (including coding conventions) and some more tweaks to make further work easier to cope with.

Please advise.

**Comment by a2geek** [comment]
Closing out as PR #19 resolves.

**Comment by Lisias** [comment]
About that First Aid tool. Should I open a issue for that to document the idea? It will be some time until I have the time to do that, but it would be nice to have it documented so I (or anyone else that like the job) can execute it without reverse-engineering the wheel. :-)
