### ISSUE TITLE
sourceZip target does not work (missing web directory)

### ISSUE THREAD

**Issue by iKarith** [AppleCommander/AppleCommander#2]
The web target in build.xml does not work as-is.  I see a couple of options here:

1. Make the web target conditional upon the availability of the web directory
2. Set up a git submodule to pull web in from its own git module
3. Do both, which will cause people not to need to mess with submodules for the general user case.

Thoughts?

**Comment by a2geek** [comment]
Ha, busted!  For the GitHub pages, I moved the web target to the [applecommander.github.io](https://github.com/AppleCommander/applecommander.github.io) project.  This way, the project site is published whenever a commit occurs.

**Comment by a2geek** [comment]
I'm thinking this is clean up activity.  Both in the make and directions...

**Comment by iKarith** [comment]
Clairification.

Should the sourceZip target then be simply modified to remove the inclusion of the web directory?  I can do that in my next round.

**Comment by a2geek** [comment]
Hold off a little bit on this. Partly due to the fact that GitHub itself packages source up into the release section but also because I'm pondering switching out of Ant (so 2000's! 😉) and into Maven or Gradle.  It was suggested I try Gradle, so I'm tinkering with it.

**Comment by iKarith** [comment]
I don't know anything about either one to be honest, willing to learn to
use either one, but I'd rather focus my efforts on getting the code working
with SWT or not needing it.

Joseph

**Comment by a2geek** [comment]
Hey @iKarith - Take a peek at the [1.4.0 BETA](https://github.com/AppleCommander/AppleCommander/releases/tag/v1-4-0-beta) release.  I think part of the question and discussion is there.  The SWT builds should be functional. Also, the Gradle is pretty much working.  I've been using `./gradlew clean test assemble`.

**Comment by iKarith** [comment]
My apologies for not getting back to this literally a month ago.  I would say that the gradle build system completely eliminates this entirely.  The issue was that the "normal" build process didn't work before.  It does now.  :)
