### ISSUE TITLE
Part of build.gradle needs to be conditional?

### ISSUE THREAD

**Issue by iKarith** [AppleCommander/AppleCommander#24]
I haven't poked at this in awhile (a lot on my plate) and came back to it to run:

```
tjcarter@chiyo:~/Source/AppleCommander/AppleCommander$ ./gradlew acJar                             

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/tjcarter/Source/AppleCommander/AppleCommander/build.gradle' line: 168           

* What went wrong:
A problem occurred evaluating root project 'AppleCommander'.                                       
> Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

That property isn't set for me and shouldn't be probably from what a quick look showed me.

**Comment by a2geek** [comment]
I was wondering about that! ;-)

I *think* that maybe the ShrinkItArchive project was setup better.  Can you give that a whirl for a build (at some point).  If it works, it can be back-ported here.

Otherwise, they both should be fixed.

These are my first Gradle projects, so not too surprised there are rough edges.

Thanks for checking!

**Comment by iKarith** [comment]
No problem, I'll have a look later today.  Once you've got gradle all
working the way you want it, maybe you can offer David some help with
ADTPro.  (I dunno if he'll want it…  But I've generally been happy with
what you've done with AppleCommander!)

Joseph

**Comment by iKarith** [comment]
Okay for this I started with the assumption that running ./gradlew with no target should fail because I'm not set up for signing and deployment.  Indeed it does:

```
tjcarter@chiyo:~/Source/AppleCommander/ShrinkItArchive$ ./gradlew 
Downloading https://services.gradle.org/distributions/gradle-4.6-bin.zip
......................................................................
Unzipping /Users/tjcarter/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6-bin.zip to /Users/tjcarter/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo
Set executable permissions for: /Users/tjcarter/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/tjcarter/Source/AppleCommander/ShrinkItArchive/build.gradle' line: 50

* What went wrong:
A problem occurred evaluating root project 'ShrinkItArchive'.
> Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

However I get the same result when I run `./gradlew jar`, which I'd expect to work.  Ideally signing and deployment should be part of the default target.  You should have to ask for that separately, and it should be okay for everything else if you can't do it.

Does cloning the repo in a separate directory cause it to emit the same error for you?

**Comment by a2geek** [comment]
After consulting with the all-powerful Google, and tinkering on my Mac (which is not setup to post to Maven Central), I think this might fix it.  Committed to both the AppleCommander and ShrinkItArchive.  Please validate on your side when you have a couple of spare minutes.  Thanks!

**Comment by iKarith** [comment]
That's how that's done?  Good to know, thanks.  Issue resolved.  :)
