### ISSUE TITLE
Error when trying to insert applesingle files created by asu

### ISSUE THREAD

**Issue by KrisKennaway** [AppleCommander/AppleCommander#28]
I tried manually creating an AS file using the asu utility, but applecommander is throwing an error when trying to insert it into a disk with ac:

$ java -jar ~/bin/AppleCommander.jar -pro140 test.dsk test
$ echo "Hello world" > test.txt
$ java -jar ~/bin/applesingle-tools-asu-1.2.1.jar create test.as --name test --filetype TXT --data-fork=test.txt
Saved to 'test.as'.
$ java -jar ~/bin/AppleCommander.jar -as test.dsk < test.as
Error: Unknown entry type of 0003
java.io.IOException: Unknown entry type of 0003
	at com.webcodepro.applecommander.util.AppleSingle.load(AppleSingle.java:66)
	at com.webcodepro.applecommander.util.AppleSingle.<init>(AppleSingle.java:34)
	at com.webcodepro.applecommander.ui.ac.putAppleSingle(ac.java:286)
	at com.webcodepro.applecommander.ui.ac.putAppleSingle(ac.java:278)
	at com.webcodepro.applecommander.ui.ac.main(ac.java:140)
	at com.webcodepro.applecommander.ui.AppleCommander.main(AppleCommander.java:83)

**Comment by a2geek** [comment]
I think I was aware of this but utterly forgot to update AppleComander!  I do have a release that is pending. I got distracted a bit, unfortunately. I'll try to pull the two versions together again.

**Comment by a2geek** [comment]
It does look like this will be better with AC 1.5.

Sample run:

```
$ ac
CommandLineHelp = AppleCommander command line options [1.5.0-BETA]:
<snip>
$ ac -pro140 test.dsk test
$ echo "Hello world" > test.txt
$ asu create test.as --name test --filetype TXT --data-fork=test.txt
Saved to 'test.as'.
$ ac -as test.dsk < test.as
$ ac -ll test.dsk
test.dsk /TEST/
  TEST  Destroy Read Rename Write TXT  001 11/21/2018 11/21/2018 12 $0000 0002 0007 Seedling  0 0 
ProDOS format; 139,264 bytes free; 4,096 bytes used.

$ ls -l test.txt    # just to show byte sizes match
-rw-r--r-- 1 rob rob 12 Nov 21 22:01 test.txt
```

**Comment by KrisKennaway** [comment]
Thank you for fixing!
