### ISSUE TITLE
Option to strip high bits on text files

### ISSUE THREAD

**Issue by gray-space** [AppleCommander/AppleCommander#33]
Thanks for adding the ability to fix line endings in text files! Now, I hit a new snag: Kyan Pascal demands that all text files have their high bit stripped. Would it be possible to add a new flag that strips the high-bit from text files being added via the -pt command?

**Comment by a2geek** [comment]
Just added an option. Do you need a copy to try out or can you build it yourself?

**Comment by gray-space** [comment]
Looks like it's working great! I removed some code I had in a python script to strip the high bits from the text files it fed into the Kyan disk image and used the -ptx option instead. Kyan pascal seems happy with the source files. Thanks!

**Comment by a2geek** [comment]
Good to hear!  It will be "official" with 1.5.1 then. :-)
