### ISSUE TITLE
AppleCommander doesn't recognize .dsk, .dsk.gz, .do, .do.gz, or .po images

### ISSUE THREAD

**Issue by philgoetz** [AppleCommander/AppleCommander#35]
When I run the 64-bit windows version, and try to Open a file, and go to the directory with my disk images, it doesn't recognize anything I have as a disk image.  I made some of these images myself, and downloaded others from a variety of sites, so I don't think the problem is with the images.

**Comment by a2geek** [comment]
Interesting. There have been past issues with the file dialog. But that was related to upper/lower case, and it _shoud_ be resolved at this point.

Do other directories "work"?  Trying to get an idea of what might be going on.  

You're going to make me get my fingers on a Windows device, aren't you? :joy:

**Comment by philgoetz** [comment]
I can use the gui to move around in different directories, if that's what
you mean. But no files ever appear available for selection.
I just checked now if this were some difficulty with Windows' bizarre
access-control lists, but it seems not.

But this is only for "Open". I was able to use "Compare" to compare two
disk images.

**Comment by a2geek** [comment]
Ah, that may be helpful! I noticed that the compare does *not* do anything with filters where the open dialog does. I also noticed that the filter setup has a new mechanism to set the default filter... so I'm setting the initial filter to the first item in the array.

I don't see this behavior on Linux, so all I can say for certain is that it "didn't break anything". 

I'll attach a PRE35, if you could give it a try. I did compile it with Java 11, so if that's a problem let me know and I can build with Java 8. I'm just being a bit lazy. ;-)

**Comment by a2geek** [comment]
I had to zip it for GitHub to allow it!

[AppleCommander-linux64-gtk-1.5.1-PRE35.zip](https://github.com/AppleCommander/AppleCommander/files/3678955/AppleCommander-linux64-gtk-1.5.1-PRE35.zip)

**Comment by philgoetz** [comment]
On Tue, Oct 1, 2019 at 8:15 PM A2 Geek <notifications@github.com> wrote:

> I'll attach a PRE35, if you could give it a try. I did compile it with
> Java 11, so if that's a problem let me know and I can build with Java 8.
> I'm just being a bit lazy. ;-)
>

What's a PRE35, and why did you send me the linux version?

>

**Comment by a2geek** [comment]
Because my memory is the size of a goldfish? :joy: 

The build scripts automatically place a version onto the build, so I don't want it to be confused with an actual release. "pre" being a pre-release and 35 being the ticket number.

Try this one:
[AppleCommander-win64-1.5.1-PRE35.zip](https://github.com/AppleCommander/AppleCommander/files/3683766/AppleCommander-win64-1.5.1-PRE35.zip)

**Comment by philgoetz** [comment]
Sorry--same results.

**Comment by a2geek** [comment]
Ok. I'll bust out a Windows laptop this weekend. 

Anything interesting in the file names you're looking at? All upper-case? Weird characters?

**Comment by philgoetz** [comment]
Here's the contents of an example directory:

-rwxrwxr-x+ 1 phil None 140K Sep  4  2018 '27B AAL'$'\177\177\177''.dsk'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 '34 Last Stand working, VCR.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 '43 NIBBLE PROSPECTS.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018  43.bak.DSK*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 '53 VARCROSSREF, work in
progress.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 '54 THRESHOLD incomplete
crack.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'ARCTIC TEXT2SPEECH A.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'ARCTIC TEXT2SPEECH B.DSK'*
-rwxrwxr-x+ 1 phil None 140K Sep  2  2018  CODE-ADVLANG,8QUEENS.dsk*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'COMPUTIST 66.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'COMPUTIST ARTICLES.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'CRACKING TECH 83.bak.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'CRACKING TECHNIQUES 1983.dsk'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018  HACKERDOS.DSK*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018  HCARTICLES.DSK*
-rwxrwxr-x+ 1 phil None 140K Aug 31  2018 'INMATE 1987 V4$10.dsk'*
-rwxrwxr-x+ 1 phil None 140K Aug 31  2018 'INMATE S6D1.dsk'*
-rwxrwxr-x+ 1 phil None 140K Aug 31  2018 'INMATE S6D2.dsk'*
-rwxrwxr-x+ 1 phil None  64K Sep  2  2018 'INMATE SOURCE D2 1987.po'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'INMATE SRC A.dsk'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'INMATE STUFF-SUBS+INSTR.DSK'*
-rwxrwxr-x+ 1 phil None 140K Sep  3  2018 'LAST STAND WI MODULES.dsk'*
-rwxrwxr-x+ 1 phil None 140K Sep  4  2018 'LASTSTAND 180902.DSK'*
drwxrwxr-x+ 1 phil None    0 Oct  1  2018 'laststand 2018'/
-rwxrwxr-x+ 1 phil None 140K Sep  1  2018 'LASTSTAND 2018.0.DSK'*
-rwxrwxr-x+ 1 phil None 140K Sep  5  2018 'LASTSTAND 2018.1.DSK'*
-rwxrwxr-x+ 1 phil None 140K Oct  5  2018 'LASTSTAND 2018.2.DSK'*
-rwxrwxr-x+ 1 phil None 140K Dec 11  2018 'LASTSTAND 2018.DSK'*
-rwxrwxr-x+ 1 phil None 140K Sep  5  2018 'LS JAPANESE.DSK'*
-rwxrwxr-x+ 1 phil None 140K Sep  1  2018 'LS MODULES.DSK'*
-rwxrwxr-x+ 1 phil None 140K Sep  2  2018 'LS ProDOS files.DSK'*
-rwxrwxr-x+ 1 phil None 140K Oct  5  2018 'LS SPANISH.DSK'*
-rwxrwxr-x+ 1 phil None 841K May  4 02:18 'Ls spanish_000000000.bmp'*
-rwxrwxr-x+ 1 phil None  108 Sep  2  2018  notes.txt*
-rwxrwxr-x+ 1 phil None 140K Aug 31  2018 'PHIL GRAD CS.DSK'*
-rwxrwxr-x+ 1 phil None 140K Sep  2  2018 'SC MACROASM WI DEBUG errs.dsk'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'SPEECH RULES.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 31  2018  TASKMASTER.dsk*
-rwxrwxr-x+ 1 phil None 800K Sep  2  2018  Virtual.po*
-rwxrwxr-x+ 1 phil None 800K Sep  2  2018  Virtual2.po*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'WRITERS INSPECTOR.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'WRITERS SUPERTEXT.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'WRITING 102 QUERIES, ARCTEC
BILLS.DSK'*
-rwxrwxr-x+ 1 phil None  15K Aug 30  2018 'WRITINGS B EOAPL,DSKSCN.DSK'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018 'WRITINGS CHAUCER.dsk'*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018  WRITINGS-AMP,EX,3RDCHILD.DSK*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018
 WRITINGS-BLIEV,TOCQ,NIETZSCHE,BUDDHAI.dsk*
-rwxrwxr-x+ 1 phil None 140K Aug 30  2018  WRITINGSC-HARDY,MARX.DSK*

**Comment by a2geek** [comment]
Ok, my wife was laughing while I cursed my way through Windows. ;-)

The good news is that I see exactly the same behavior (so nothing really obtuse). From some poking around, I suspect that the case insensitivity ticket from a while ago ("dsk" versus "DSK" for instance) look like they are breaking the Windows filters. I'm not certain if it's just not supported for Windows or if AppleCommander itself has a weird bug. I'll continue to poke at it and attach a build that looks promising once I get there!

For now, there is a file filter you can change in the open files dialog -- just pick "All Files" and it should show every file.

**Comment by a2geek** [comment]
This *should* fix it. Please try the attached copy!

[AppleCommander-win64-1.5.1-PRE35.zip](https://github.com/AppleCommander/AppleCommander/files/3693676/AppleCommander-win64-1.5.1-PRE35.zip)

**Comment by a2geek** [comment]
I think this has been addressed. I want to get the next release out, so closing. If it's not resolved in 1.6.0, feel free to re-open.

**Comment by philgoetz** [comment]
> This _should_ fix it. Please try the attached copy!
> 
> [AppleCommander-win64-1.5.1-PRE35.zip](https://github.com/AppleCommander/AppleCommander/files/3693676/AppleCommander-win64-1.5.1-PRE35.zip)

Sorry I didn't reply earlier. No luck with 1.5.1.
I went to download version 1.6.0, but the files on github don't have version numbers.
I don't see any way to tell what version# the current release is.
