### ISSUE TITLE
Dangerous check-java-versions.sh script in tools

### ISSUE THREAD

**Issue by bernstbj** [AppleCommander/AppleCommander#40]
Though it is a minor tool, I did notice that the tools/check-java-versions.sh will do an 'rm -rf /' if not run on a GNU/Linux system. In particular, the use of 'mktemp --directory' is utilizing the GNU-specific '--directory' instead of the more universal '-d' argument. This will result in a failure and subsequently the script will do a 'rm -rf /' because it doesn't check to see if the operation succeeded.

Simple below:

```
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-TMP=$(mktemp --directory)
+TMP=$(mktemp -d)
+if [ -z ${TMP} ];
+then
+    echo "Problem creating TEMP directory; aborting!"
+    exit 1
+fi

```

**Comment by a2geek** [comment]
Wow, thanks! Just committed the patch.
