### ISSUE TITLE
Access timestamp of files?

### ISSUE THREAD

**Issue by gray-space** [AppleCommander/AppleCommander#42]
Hiya! So, I have a use case for knowing the timestamp of a file in a disk image. Basically, I want to compare the timestamp of a file in the image with one of a file outside in the host filesystem. If the filesystem is a newer file, I want to have a script update the file in the image.

Using the -ll command doesn't seem to give this to me. There is some added data in the output each file that I can't decipher. For example:

`TITLELOAD.P  Destroy Read Rename Write TXT  016 06/05/2020 06/05/2020 7,304 $0000 0359 0ABD Sapling Changed 0 0 `

Looking at the disk image in Ciderpress, I see that the file's timestamp is 17:18. I can;t figure out a way you'd get that value from either 0359 or 0ABD. Do they reflect the timestamp somehow? If not, is there a way to access the timestamps of the files in the image?

**Comment by a2geek** [comment]
Those numbers actually are internal pointers withing the ProDOS disk... but you're right, the timestame is not shown.

The code that is currently being used is actually for the GUI and the [ProDOS code is here](https://github.com/AppleCommander/AppleCommander/blob/master/src/main/java/com/webcodepro/applecommander/storage/os/prodos/ProdosFileEntry.java#L400) if you're curious.

If you're processing this, what format would work for you for scripting? I typically do a lot with JSON and `jq` but I'm not certain what other folks use. Maybe a CSV type format?  I'm thinking this free-form text isn't really appropriate. 

It might be time to add another list option!

**Comment by gray-space** [comment]
Just about any format would do... short of a raw binary blob. CSV would be easy to split up. A simple text string is fine too, as there are libraries to parse most of the commonly-used formats. JSON would also work.

**Comment by a2geek** [comment]
Went a little overboard, so hopefully this helps out. Also introducing some CSV and JSON goodness. 

For ProDOS, I added the timestamp to the `-ll` format.

```
% ac -ll ~/Downloads/ProDOS_2_4_2.dsk                                                 
/Users/rob/Downloads/ProDOS_2_4_2.dsk /PRODOS.2.4.2/
  VIEW.README  Destroy Read Rename Write BAS  001 09/15/2016 09:26 01/13/2018 09:09 512 A=$0801 0002 0116 Seedling Changed 0 36
* BITSY.BOOT  Read  SYS  001 09/15/2016 09:49 01/13/2018 09:09 365 A=$2000 0002 003D Seedling Changed 0 36
<snip>
```

Also, throwing a `v` on the end yields CSV:

```
% ac -llv ~/Downloads/ProDOS_2_4_2.dsk
/Users/rob/Downloads/ProDOS_2_4_2.dsk,/PRODOS.2.4.2/
" ",Name,Deleted?,Permissions,Filetype,Directory?,Blocks,Modified,Created,Length,Aux. Type,Dir. Header,Key Block,Key Type,Changed,Min. ProDOS Ver.,ProDOS Ver.
" ",VIEW.README,,Destroy Read Rename Write,BAS,,001,09/15/2016 09:26,01/13/2018 09:09,512,A=$0801,0002,0116,Seedling,Changed,0,36
*,BITSY.BOOT,,"Read ",SYS,,001,09/15/2016 09:49,01/13/2018 09:09,365,A=$2000,0002,003D,Seedling,Changed,0,36
```

And finally, coupling the `ac -llj <image>` with `jq` allows some additional selection capabilities... I continued to just use the output of the other commands instead of reimplementing that portion. Meaning they are strings and not their actual data types as well as being formatted for the listing and viewing commands. 

```
% ac -llj ~/Downloads/ProDOS_2_4_2.dsk | jq -r '.disks[0].files[] | select(.name == "README")'
{
  "locked": " ",
  "name": "README",
  "deleted": "",
  "permissions": "Destroy Read Rename Write",
  "type": "TXT",
  "directory": "0002",
  "blocks": "001",
  "modified": "01/18/2018 06:54",
  "created": "01/13/2018 09:09",
  "size": "497",
  "auxType": "$0000",
  "keyBlock": "0117",
  "keyType": "Seedling",
  "changed": "Changed",
  "minimumProdosVersion": "0",
  "prodosVersion": "36"
}
```

**Comment by a2geek** [comment]
It's dumb that we can't attach a `.jar` but we can a `.zip`? Sample in the zip file.
[AppleCommander-ac-1.7.0pre.jar.zip](https://github.com/AppleCommander/AppleCommander/files/5578521/AppleCommander-ac-1.7.0pre.jar.zip)

**Comment by gray-space** [comment]
Got this working perfectly,. I now have a short python script that calls AppleCommander to figure out what files have been altered locally, and then update them in an image. This will save me considerable time when editing outside the image and compiling inside it. Thanks!
