### ISSUE TITLE
Open UI with command line switch argument

### ISSUE THREAD

**Issue by webspacecreations** [AppleCommander/AppleCommander#47]
A very handy feature would be the ability to "Open with..." and auto-load the selected image into the graphical UI. The existing switches are very powerful, but don't appear to cover this (non-technical user) use case.

e.g. java -jar build/libs/AppleCommander-linux64-gtk-1.7.0.jar -f=/path/to/file
-or maybe (to distinguish from non-GUI argments):
java -jar build/libs/AppleCommander-linux64-gtk-1.7.0.jar -uiopen=/path/to/file

My preliminary attempts to add the switch failed (all the existing switches appear to focus on the command line tool), but I attribute that to not being a Java dev.

**Comment by a2geek** [comment]
I like this idea!  There is already a command-line switch in place, so I'm just utilizing that.  `-swt` is that switch. I added the capability for SWT to launch multiple windows. 

I'm currently working from my Mac, and this did indeed launch AppleCommander in GUI mode with two disk windows already open:

```
 % java -XstartOnFirstThread -jar ./build/libs/AppleCommander-macosx-1.7.0pre.jar -swt ~/Downloads/ProDOS_2_4_2.dsk ~/Dropbox/Apple2/APPLE-II-DISK-IMAGES/games/rpg/APSHAI.DSK 
```

Hopefully this carries over to the other operating systems! 
[AppleCommander-ticket47-early-builds.zip](https://github.com/AppleCommander/AppleCommander/files/5578541/AppleCommander-ticket47-early-builds.zip)
