### ISSUE TITLE
Extend the "Compare" function?

### ISSUE THREAD

**Issue by Kirkman** [AppleCommander/AppleCommander#48]
Hi, I'm new to Apple Commander. I'm running the Java applet on Mac OS X.

The "Compare..." function is useful, but it's extremely limited. As far as I can see, it will only tell if two images are identical or not.

Would you consider beefing this up some? Maybe show which specific files are different between two images? 

Even better would be to use diff to show the portions of a file (or a directory) that differ between two disk images.

**Comment by a2geek** [comment]
This is a good idea. As a thought experiment, maybe there are different types of comparisons that can be done.
* Block level; track/sector level for exact disk comparisons.
* File level; compare each file based on file name. Likely has some twists based on OS (aka DOS and ProDOS comparisons are possible and maybe useful), but all of them should be able to compare based on bytes in the file. Obviously, filenames must match.

No commitment to the diff but I think the above is possible. I also noticed that this isn't in `ac` or `acx` so it would be nice to expand the capability into those tools!
