### ISSUE TITLE
Adding files to ProDOS image does not overwrite existing files

### ISSUE THREAD

**Issue by gray-space** [AppleCommander/AppleCommander#53]
A new wrinkle in developing a workflow for editing on a modern system and compiling within an emulator. If you tell ac to add a file to an image that already has a file with that name, it will add a new file with the same name rather than overwriting the existing file. For example:

```$ ac -pro800 test.po test
$ ac -p test.po collar.jpg BIN < collar.jpg 
$ $ ac -ll test.po
test.po /TEST/
  COLLAR.JPG  Destroy Read Rename Write BIN  792 04/04/2021 08:26 04/04/2021 08:26 402,479 A=$2000 0002 0109 Tree  0 0
ProDOS format; 410,112 bytes free; 409,088 bytes used.
$ ac -p test.po collar.jpg BIN < collar.jpg 
$ ac -ll test.po 
test.po /TEST/
  COLLAR.JPG  Destroy Read Rename Write BIN  792 04/04/2021 08:26 04/04/2021 08:26 402,479 A=$2000 0002 0109 Tree  0 0
  COLLAR.JPG  Destroy Read Rename Write BIN  792 04/04/2021 08:26 04/04/2021 08:26 402,479 A=$2000 0002 0421 Tree  0 0
ProDOS format; 4,608 bytes free; 814,592 bytes used.
```

This also happens for -pt and -ptx. 

I've not tested other image formats like DOS 3.3. So, this may be isolated to ProDOS.

Interestingly, nothing in ProDOS seems to mind multiple identically-named files... the shell I am using on the Apple II seems perfectly content to access one of the copies of the file. If I use a command to delete a file with the duplicate filename, it deletes one copy and leaves the other in place. Telling ac to delete the filename from the image does the same: it deletes one copy and leaves the other one there.

This isn't a huge issue, as I'll just have the script I've written to update files in the ProDOS image check for an existing copy of a file and delete it before adding an updated copy. But it might confuse people who are expecting that adding a file to an image will overwrite an existing file in the image, rather than creating a duplicate with the same name.

**Comment by ryandesign** [comment]
This behavior is documented here: https://applecommander.github.io/ac/#known-problems-limitations

**Comment by a2geek** [comment]
This is a general behavior with the `ac` tool. I was already working on a new "experimental" CLI tool as an upgrade, and I've incorporated these notes. (hopefully -- first release may contain bugs!)

A sample run if you're curious...

First, create a `STARTUP` program...
```
% acx import -d test.po --basic program1.bas --name=startup
% acx ls -d test.po                                        

File: test.po
Name: /NEW.DISK/
* PRODOS          SYS      035 01/10/2022 01/13/2018     17,128          
* BASIC.SYSTEM    SYS      021 01/10/2022 01/13/2018     10,240 A=$2000  
  STARTUP         BAS      001 01/10/2022 01/10/2022         19 A=$0801  
ProDOS format; 110592 bytes free; 32768 bytes used.
```

Next, try to update `STARTUP` ...
```
% acx import -d test.po --basic program2.bas --name=startup
File 'startup' exists.
% acx ls -d test.po                                        

File: test.po
Name: /NEW.DISK/
* PRODOS          SYS      035 01/10/2022 01/13/2018     17,128          
* BASIC.SYSTEM    SYS      021 01/10/2022 01/13/2018     10,240 A=$2000  
  STARTUP         BAS      001 01/10/2022 01/10/2022         19 A=$0801  
ProDOS format; 110592 bytes free; 32768 bytes used.
```
No change (based on file size not changing).

Then, force an over-write.
```
% acx import -d test.po --basic program2.bas --name=startup --force
% acx ls -d test.po                                            

File: test.po
Name: /NEW.DISK/
* PRODOS          SYS      035 01/10/2022 01/13/2018     17,128          
* BASIC.SYSTEM    SYS      021 01/10/2022 01/13/2018     10,240 A=$2000  
  STARTUP         BAS      001 01/10/2022 01/10/2022         27 A=$0801  
ProDOS format; 110592 bytes free; 32768 bytes used.
```
And it changed.
