### ISSUE TITLE
How to set the Aux. Type?

### ISSUE THREAD

**Issue by audetto** [AppleCommander/AppleCommander#55]
I would like to set the `Aux. Type` to $0641 like 
![Screenshot from 2021-06-12 18-58-34](https://user-images.githubusercontent.com/212523/121785186-33e10680-cbb0-11eb-913a-9200c423aa94.png)

I try

`java -jar ${AC} -p disk.po prog $f1 0x0641 < data`

but it is always 0x0000

I am using 1.6.0

**Comment by audetto** [comment]
I seem to have found: the aux type is honoured only if it is allowed in this file https://github.com/AppleCommander/AppleCommander/blob/febe3d9f75399bf16eaa8e6aadf12db08fd93cd1/src/main/resources/com/webcodepro/applecommander/storage/os/prodos/ProdosFileTypes.properties

Is there a way to force the aux type regardless of the content of the above file?

**Comment by a2geek** [comment]
In `ac` that's really the address and is setup to use that. I did look at a new CLI took (`acx`) being built out and it did the same thing. In that case, I added a flag to set aux type (as opposed to address) which would set the value every time.
