### ISSUE TITLE
Build fails with gradle 7: Plugin [id: 'maven'] was not found

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#56]
Building with `gradle assemble` (with gradle 7.2 installed) fails:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/path/to/AppleCommander-1-6-0/build.gradle' line: 4

* What went wrong:
Plugin [id: 'maven'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/7.2/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (plugin dependency must include a version number for this source)

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

I understand that [the maven plugin has been removed in gradle 7](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html?_ga=2.5711415.522454420.1632276142-917694635.1632276142#removal_of_the_legacy_maven_plugin) and you should use [the maven-publish plugin](https://docs.gradle.org/7.0/userguide/publishing_maven.html) instead.

Since the maven stuff seems to relate to publishing new versions of this software, which I don't need to do, I tried removing `id 'maven'` from the `plugins` block and the entire `uploadArchives` block but there are further errors. Perhaps updating to gradle 7 is more involved. I know nothing about gradle so I can't help.

-----

The build works if I use `./gradlew assemble` but this downloads a copy of gradle at build time and I would rather use the copy of gradle I already have installed.

**Comment by a2geek** [comment]
AppleCommander just updated the Gradle dependencies to 7.3, so that should help. I don't think anything can be done related to version differences between installations (that's the point of using the project Gradle version via `./gradlew`). 

I will admit I'm not a Gradle expert either -- lots of searching and trying to get things done!

I'm now using `build` (not certain what the difference is):
```
$ ./gradlew clean build

BUILD SUCCESSFUL in 10s
105 actionable tasks: 105 executed
```
Also note that with the project restructuring now using subprojects, the resulting files have moved around.
```
 find ./app -name "AppleCommander*.jar"
./app/gui-swt-macosx-aarch64/build/libs/AppleCommander-macosx-aarch64-1.7.0-SNAPSHOT.jar
./app/gui-swt-win32-x86_64/build/libs/AppleCommander-win32-x86_64-1.7.0-SNAPSHOT.jar
./app/gui-swt-linux-x86_64/build/libs/AppleCommander-linux-x86_64-1.7.0-SNAPSHOT.jar
./app/cli-acx/build/libs/AppleCommander-acx-1.7.0-SNAPSHOT.jar
./app/gui-swt-macosx-x86_64/build/libs/AppleCommander-macosx-x86_64-1.7.0-SNAPSHOT.jar
./app/gui-swing/build/libs/AppleCommander-swing-ui-1.7.0-SNAPSHOT.jar
./app/gui-swt-linux-aarch64/build/libs/AppleCommander-linux-aarch64-1.7.0-SNAPSHOT.jar
./app/cli-ac/build/libs/AppleCommander-ac-1.7.0-SNAPSHOT.jar
```

**Comment by ryandesign** [comment]
I'll close this since you've fixed the incompatibility with gradle 7.
