### ISSUE TITLE
Choose name other than "ac" for the command line utility

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#57]
Your documentation and examples suggest that the user should set up `ac` as an alias for running the AppleCommander CLI, but `ac` is already the name of a built-in program on BSD Unix systems like macOS:

> A record of individual login and logout times are written to the system log by login(8) and launchd(8), respectively.  The program `ac` examines these records and writes the accumulated connect time (in decimal hours) for all logins to the standard output.

I suggest you select a longer more-unique name for your program. I see that Homebrew is already installing it as `applecommander`; perhaps that would be a good choice. Shell completion features make entering long names not much of a problem and a user can always create a shorter alias if it suits them.

Your companion programs `bt` and `st` might also benefit from more-unique names. A quick search showed other existing `st` programs.

You can reduce confusion and increase adoption of whatever names you select by actually providing wrapper scripts of these names rather than just suggesting the use of aliases in the documentation.

**Comment by a2geek** [comment]
I did make a note for this at https://applecommander.github.io/install/#command-line - personally, I prefer `ac` versus `applecommander` but it's fair to note this should be called out.

**Comment by a2geek** [comment]
Closing since I think this question was addressed.
