### ISSUE TITLE
Prevent illegal filenames

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#59]
Using AppleCommander 1.6.0 I created a DOS 3.3 DOS order disk. Not remembering what the DOS filename restrictions were, I placed some files on the disk image whose names began with digits. Turns out DOS filenames must begin with a letter and because my files didn't, trying to BLOAD them at the BASIC prompt resulted in a ?SYNTAX ERROR. To reduce confusion, AppleCommander should prevent adding files with illegal filenames (or renaming existing files to illegal filenames). ProDOS may have different filename restrictions than DOS.

**Comment by a2geek** [comment]
Thanks for the find!  I poked around (it's been a while) and realized that the AppleCommander runs through the logic to check filenames but `ac` (the command-line tool) doesn't. I updated the DOS name checks and tweaked the other two (ProDOS and Pascal).
