### ISSUE TITLE
Allow specifying order when creating disk images on the command line

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#61]
On the command line `-dos140` creates a DOS-order DOS-formatted disk (.dsk extension) while `-pro140` creates a ProDOS-order ProDOS-formatted disk (.po extension). There does not appear to be a way to create, for example, a DOS-order ProDOS-formatted disk with the command line. Since this capability exists in the GUI I presume there is a reason why a user would want to do this, so the capability should be offered in the CLI as well.

**Comment by a2geek** [comment]
Good catch. There is a new CLI `acx` coming, and the `create` subcommand will have the capability to set the order scheme.
