### ISSUE TITLE
Format bootable ProDOS disk

### ISSUE THREAD

**Issue by pinobatch** [AppleCommander/AppleCommander#63]
I'm trying to use cc65, AppleCommander, and LinApple to develop an Apple II program. I seek to build a `make run` recipe that formats a disk image, puts the needed files on the disk, and runs it. I'm to the point where I can build a disk image of my program, boot ProDOS 2.4 from <https://prodos8.com/> in drive 1 with my program in drive 2, and `BRUN MYPROGRAM,D2` from the BASIC prompt.

I tried to refine the process without having to type that every time. A snag I ran into is that ProDOS doesn't appear to boot from a disk image formatted with AppleCommander 1.6.0 on OpenJDK 17 on Xubuntu 21.10.
```
# Format the disk
java -jar ac -pro140 run.po RUN
# Copy two files from ProDOS 2.4
java -jar ac -g ProDOS_2_4.dsk PRODOS | java -jar ac -p run.po PRODOS sys 0x2000
java -jar ac -g ProDOS_2_4.dsk BASIC.SYSTEM | java -jar ac -p run.po BASIC.SYSTEM sys 0x2000
# Boot the disk
linapple -1 run.po -r
```
Instead of the expected `PRODOS BASIC` prompt, I get this
```
APPLECOMMANDER CREATED THIS DISK
VISIT APPLECOMMANDER.GITHUB.IO

INSERT ANOTHER DISK AND PRESS ANY KEY
```
Is there a way to format a bootable disk using AppleCommander? Or did I miss some documentation about the lack of bootability?

**Comment by pinobatch** [comment]
Current workaround: Copy the boot sector from the ProDOS 2.4 disk after copying the boot files
```
# AppleCommander's boot sector isn't bootable; ProDOS 2.4's is.
# ProDOS 2.4 also ships as a DOS 3.3-ordered image for some reason.
# Copy ProDOS 2.4 boot sector
dd conv=notrunc bs=256 if=$PRODOSDISK of=run.po count=1 skip=0 seek=0
dd conv=notrunc bs=256 if=$PRODOSDISK of=run.po count=1 skip=14 seek=1
```

**Comment by a2geek** [comment]
Hey @pinobatch - That's not a bad solution. AppleCommander has never really dealt with the boot block / operating system machinations. If you're good with it, I'd like to leave this open as a reminder to possibly address within the tooling. I suspect the best mechanism will be to provide disk "masters" for the writable operating systems (DOS / ProDOS / Pascal) instead of trying to code for a specific type of boot sector / block.

**Comment by a2geek** [comment]
Noting that a new tool coming with the next release is an enhanced command-line utility (acx) and it should help this process out quite a bit!  I left my notes in a README buried [here](https://github.com/AppleCommander/AppleCommander/blob/master/app/cli-acx/README.md#sample-run).
