### ISSUE TITLE
Invisible text in dark mode

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#67]
When macOS (10.14 or later) are set to dark mode (System Preferences > General > Appearance > Dark), the AppleCommander 1.6.0 interface is unusable because while the text is now white (appropriate for dark mode's customary dark backgrounds), the background is still white too.

![Screen Shot 2022-01-16 at 14 56 17](https://user-images.githubusercontent.com/429209/149677840-8b49ec2f-28cb-4304-9d7c-3c27c60625bf.png)

**Comment by a2geek** [comment]
Ick! When you have a chance, please check out AppleCommander 1.7; there was a bump to the SWT libraries and it (at least on my mac) handle the dark mode better. 

However, I'm also noticing that the text seems to get hidden a bit behind the images in the wizard screens and I'd like a secondary guage on that (my other Mac died, so I just have the M1 mac).

**Comment by ryandesign** [comment]
It's legible in dark mode with AppleCommander 1.8.0 on macOS Monterey 12.6.8.

![About box](https://github.com/AppleCommander/AppleCommander/assets/429209/5febd250-9646-4b41-a770-ff43af411081)

I'll file a separate issue about the text positioning in the wizards.
