### ISSUE TITLE
Quits instead of creating disk image

### ISSUE THREAD

**Issue by ryandesign** [AppleCommander/AppleCommander#68]
On macOS 10.15.7, I'm not able to create a disk image.

To reproduce:

1. Launch AppleCommander 1.6.0
2. Click Create...
3. Leaving the DOS 3.3 radio button selected, click Next >
4. Type TEST into the disk name field and click Next >
5. Leaving the DOS ordered radio button selected, click Finish
6. AppleCommander quits

I seem to remember this working a few months ago but I upgraded from macOS 10.13.6 to 10.15.7 since then.

**Comment by a2geek** [comment]
If you could, please try this with AppleCommander 1.7. I don't see a specific ticket for this, but there were a couple of exceptions that were crashing AppleCommander. If I remember correctly, the SWT windowing library was really really old, so part of the solution was to bump that library. I can recreate this with 1.6 but not with 1.7.

**Comment by ryandesign** [comment]
I can't reproduce the issue with AppleCommander 1.8.0 on macOS Monterey 12.6.8.
