### ISSUE TITLE
DiskFullException when there is plenty of space on disk image

### ISSUE THREAD

**Issue by nilseuropa** [AppleCommander/AppleCommander#72]
It seems like `ac` is throwing an exception if 140k is filled regardless the actual size of the image. In this case it's a 5MB HDV:

`Adding file: ZENTRUM
Error: Unable to allocate more space for another file!
com.webcodepro.applecommander.storage.DiskFullException: Unable to allocate more space for another file!
	at com.webcodepro.applecommander.storage.os.prodos.ProdosFormatDisk.createFile(ProdosFormatDisk.java:256)
	at com.webcodepro.applecommander.storage.os.prodos.ProdosFormatDisk.createFile(ProdosFormatDisk.java:201)
	at com.webcodepro.applecommander.storage.os.prodos.ProdosFormatDisk.createFile(ProdosFormatDisk.java:51)
	at com.webcodepro.applecommander.ui.ac$Name.createEntry(ac.java:729)
	at com.webcodepro.applecommander.ui.ac.putAppleSoft(ac.java:227)
	at com.webcodepro.applecommander.ui.ac.main(ac.java:187)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Done.
nils@europa:~/apple/Franke$ ac.sh -i franke_prodos.hdv 
File Name: franke_prodos.hdv
Disk Name: /FRANKE/
Physical Size (bytes): 5242880
Free Space (bytes): 5167616
Used Space (bytes): 75264
Physical Size (KB): 5120
Free Space (KB): 5046
Used Space (KB): 73
Archive Order: ProDOS
Disk Format: ProDOS
Total Blocks: 10240
Free Blocks: 10093
Used Blocks: 147
Volume Access: Destroy Read Rename Write
Block Number of Bitmap: 6
Creation Date: 03/07/2022
File Entries Per Block: 13
File Entry Length (bytes): 39
Active Files in Root Directory: 51
Minimum ProDOS Version Required: 0
Volume Created By ProDOS Version: 0
Volume Name: FRANKE
`

**Comment by a2geek** [comment]
Thanks for the details posted. I suspect that the root directory is full. With a ProDOS disk, the root directory is fixed at 51 file entries. (The details you posted include the `Active Files in Root Directory: 51`.) 

This can be simulated with this sequence:
```
% ac -pro140 a.dsk TEST                     
% for N in $(seq 1 52); do echo "a bit of text" | ac -pt a.dsk file${N}; done
Error: Unable to allocate more space for another file!
<chopped out the stack trace>
% ac -l a.dsk
a.dsk /TEST/
  FILE1 TXT 001 03/09/2022 03/09/2022 14 
<cut out FILE2 through FILE50>
  FILE51 TXT 001 03/09/2022 03/09/2022 14 
ProDOS format; 113,664 bytes free; 29,696 bytes used.

 % ac -i a.dsk 
File Name: a.dsk
Disk Name: /TEST/
Physical Size (bytes): 143360
Free Space (bytes): 113664
Used Space (bytes): 29696
Physical Size (KB): 140
Free Space (KB): 111
Used Space (KB): 29
Archive Order: ProDOS
Disk Format: ProDOS
Total Blocks: 280
Free Blocks: 222
Used Blocks: 58
Volume Access: Destroy Read Rename Write
Block Number of Bitmap: 6
Creation Date: 03/09/2022
File Entries Per Block: 13
File Entry Length (bytes): 39
**Active Files in Root Directory: 51**
Minimum ProDOS Version Required: 0
Volume Created By ProDOS Version: 0
Volume Name: TEST
```

I'd double-check that `ac` isn't duplicating files. Current behavior is to just create a new entry even if the file exists. Assuming that's the case, change the build process to account for this. Alternatively, you can try `acx` which should just over-write a same-named file (`acx` is more verbose so definite command changes involved - [starter docs here](https://applecommander.github.io/acx/)).

**Comment by nilseuropa** [comment]
Yes, that was the case. 

Thank you very much for the clarification. I didn't know about the entry limit.
