### ISSUE TITLE
How to get at AntTask.class inside a springboot-packaged jar?

### ISSUE THREAD

**Issue by david-schmidt** [AppleCommander/AppleCommander#80]
I'm trying to upgrade to ac-1.7.0, but I can't figure out how to address the AntTask.  Normally, I'd address it in my `build.xml` this way:
```
<taskdef name="appleCommander" classname="com.webcodepro.applecommander.ui.AntTask" classpath="${projdir}/src;${acJarPath}/${acJar}"/>
```
But the AntTask isn't in the jar as `com/webcodepro/applecommander/ui/AntTask.class` like it used to be; now it's here: `BOOT-INF/classes/com/webcodepro/applecommander/ui/AntTask.class`

I've tried unsuccessfully to get ant to be happy with this name, but nothing I've tried works.  How do I use it in this new spring-form pan?

**Comment by a2geek** [comment]
That was one of the breaking features for this release and I wasn't certain if ant is still being used. I'll take a look at it and see what it takes to bring it back.

**Comment by david-schmidt** [comment]
Cool, thanks - I’m not at all familiar with this springboot business. The ant task should be a pretty straightforward interface to the rest of ac with just one flat class.

**Comment by a2geek** [comment]
Can you give this a whirl?  I resurrected the old ANT test script and it passed, so I think it will be good!  (GitHub doesn't allow `.jar` files so I renamed it to `.zip` -- fix the name if you need to.)

[AppleCommander-ant-1.8.0-SNAPSHOT.zip](https://github.com/AppleCommander/AppleCommander/files/8401842/AppleCommander-ant-1.8.0-SNAPSHOT.zip)

**Comment by david-schmidt** [comment]
```
BUILD SUCCESSFUL
Total time: 16 seconds
```
Works like a charm!

**Comment by a2geek** [comment]
Great!  I'll get it worked in and make an 'official' build with 1.8.0 when it gets released. Feel free to use that copy -- thanks for letting me know it's still needed!
