### ISSUE TITLE
acx -a=$1234 does not work correctly on Linux

### ISSUE THREAD

**Issue by ThomasFok** [AppleCommander/AppleCommander#91]
I tried to import an AppleSingle file to a Prodos Disk Image on a Linux machine. If I use `-a=$1234` parameter, the auxtype becomes $00EA (234) and there is no error/warning message.

If I use `-a=$0000`, I get this message:
`Invalid value for option '--addr': cannot convert '-bash000' to Integer (java.lang.NumberFormatException: For input string: "-bash000")`

It means that `$0` has been interpreted as  Bash Shell special parameter $0.

If I quote the address like `-a='$1000'`, it works. There is no such problem on Windows machines.

If this problem can't be fixed, I think it is better to remove this feature because this problem is producing incorrect result without any error/warning message and not all users realize it is necessary to quote the address in dollar sign notation.

**Comment by a2geek** [comment]
That's just usual Unix style shell variables. Nothing specific to acx. I'll take a peek at the number interpretation to see if a better message can be generated (maybe just a note about Unix shell variables).
